// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  blueBar: string;
  blueBarOne: string;
  tips: string;
  title: string;
  wrap: string;
  yellowBar: string;
}
declare let cssExports: CssExports;
export = cssExports;
